name: Blog Develop
run-name: ${{ github.actor }} is building
on: 
  push:
      branch:
            - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_CLASS_SECRETS }}
          publish_dir: ./dist
